### PR TITLE
Check if the buffer is really opened in sorters

### PR DESCRIPTION
**Pull request by aclex**
The check whether the buffer is loaded is added in the enumeration of all the buffers in the list in sorters to ensure the proper sorting.

### CODE REVIEW

**Comment by delphinus** [comment]
It is a nice catch to confirm the buffers are loaded before making candidates. I'll add commits to fix for tests. Thank you for contributing!

**Comment by aclex** [comment]
@delphinus many thanks for taking a look!

**Comment by aclex** [comment]
Sorry, I suddenly realized, that since I made a change it wouldn't hurt for me to change the unit tests accordingly :) So here's my try. Sorry for the delay with it and for any inconsistencies in the code, Lua is still an unknown dark box for me)

**Review by delphinus — APPROVED** [review]
Thank you for contribution. Your current implementation has some redundancy for calculating “git root“ and lacks unit tests for it. I will add them after merging this.

**Comment by aclex** [comment]
@delphinus many thanks for the merge it and especially for tidying up these changes with the further commit!

**Pull request merged**
