### PR TITLE
refactor: reach the master

### PR DESCRIPTION
**Pull request by delphinus**
This adds commits from the master into the `refactor` branch #35 . Needs more tests to merge.

### TODO

* [x] `db_root` option does not work.
* ~~Type annotations have many errors.~~
   - I will fix this later in another PR.
* [x] `auto_validate` works validly?

Here is notes from #35 below. I will refactor more in another PR.

----

#### Changes:

- Use sql.nvim new api to make data layer more readable.
- Move some files out telescope/_extentions/
- Create algo.lua: to be the place to store calculation or algorithms (idk feels wrong now)
- general refactoring

### CODE REVIEW

**Comment by delphinus** [comment]
Seems working now.

**Comment by sunjon** [comment]
Hi. I'm hopefully going to have time to show the plugins I wrote a bit more love now.
Thanks for all the work - this looks great!. Give me a couple of days to try read through the changes and try it out.

**Comment by delphinus** [comment]
Now this takes over #35, so changes the target to `main`.

**Comment by delphinus** [comment]
I have been dog-fooding long time, and it seems safe to merge.

**Comment by delphinus** [comment]
I have been dog-fooding long time, and it seems safe to merge.

**Comment by delphinus** [comment]
I will merge this. Another refactoring is needed.

**Comment by delphinus** [comment]
I will merge this. Another refactoring is needed.

**Pull request merged**
